# Generated by Django 3.2.4 on 2021-06-07 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='state',
        ),
    ]
