# Generated by Django 3.2.4 on 2021-06-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('todos', '0005_delete_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30)),
                ('state', models.BooleanField(default=False)),
                ('person_responsible', models.CharField(max_length=50)),
            ],
        ),
    ]
