# Generated by Django 3.2.4 on 2021-06-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0009_auto_20210608_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
