# Generated by Django 4.2.2 on 2023-06-15 06:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2, 'Model should have at least 2 characters')]),
        ),
    ]
