# Generated by Django 4.1.2 on 2022-10-13 10:05

import authapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=6)),
                ('first_name', models.CharField(max_length=20, validators=[authapp.validators.profile_name_validator], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=20, validators=[authapp.validators.profile_name_validator], verbose_name='Last Name')),
                ('profile_picture', models.URLField(blank=True, null=True, verbose_name='Profile Picture')),
            ],
        ),
    ]
