# Generated by Django 4.1.2 on 2022-10-13 10:05

import django.core.validators
from django.db import migrations, models
import myplantapp.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Outdoor Plants', 'Outdoor Plants'), ('Indoor Plants', 'Indoor Plants')], max_length=14, verbose_name='Type')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), myplantapp.validators.plant_name_validator], verbose_name='Name')),
                ('image_url', models.URLField(verbose_name='Image URL')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.IntegerField(verbose_name='Price')),
            ],
        ),
    ]
