# Generated by Django 4.0.2 on 2022-04-21 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_petsphoto_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
